### PR TITLE
Node-wide settlement engine url map + various fixes

### LINKED ISSUE #178: Add identifier for each settlement engine instance
If a settlement engine instance is ever migrated to a different port or IP address, every account linked to that settlement engine must have the URL associated with it updated. 

If there was a separate mapping of settlement engine identifiers to settlement engine URLs, each account could be linked to the immutable settlement engine identifier, and the URL would only have to be updated in a single place.

### PR DESCRIPTION
**Pull request by emschwartz**
Resolves https://github.com/interledger-rs/interledger-rs/issues/337
Resolves #178 

This also includes various fixes related to BTP, CCP, and dynamically setting the ILP address based on the ILDCP response from the parent.

### CODE REVIEW

File: crates/interledger-api/src/routes/node_settings.rs [hunk 1]
```diff
@@ -166,11 +167,31 @@ where
         })
         .boxed();
 
+    // PUT /settlement/engines
+    let put_settlement_engines = warp::put2()
```
[the remark this answers is not in the document]
Comment (emschwartz) [reply crates/interledger-api/src/routes/node_settings.rs]: Yup, good catch

File: crates/interledger-store-redis/src/store.rs [hunk 2]
```diff
@@ -1767,6 +1747,55 @@ fn update_routes(
...
+type LoadAccountsResult = (SharedConnection, Vec<AccountWithEncryptedTokens>);
+/// Load accounts from Redis
+/// Also, if an account does not have a settlement_engine_url configured
+/// but there is one configured globally for that account's asset_code,
+/// then set the account's settlement_engine_url to the global one
+fn load_accounts(
+    connection: SharedConnection,
+    account_ids: Vec<AccountId>,
+) -> impl Future<Item = (SharedConnection, Vec<AccountWithEncryptedTokens>), Error = ()> + Send {
+    // TODO can we make these two calls with one pipeline call
```
[the remark this answers is not in the document]
Comment (emschwartz) [reply crates/interledger-store-redis/src/store.rs]: Agreed. I tried for 2-3 hours this evening to make the lua script to work but couldn't get it. I will give it another try tomorrow but if I can't figure it out quickly I'll just leave a TODO about it

File: crates/interledger-store-redis/src/store.rs [hunk 3]
```diff
@@ -1767,6 +1747,55 @@ fn update_routes(
...
+            )| {
+                debug!(
+                    "settlement engines: {:?}, accounts: {:?}",
+                    settlement_engines, accounts
+                );
+                for account in accounts.iter_mut() {
+                    if account.account.settlement_engine_url.is_none() {
+                        debug!("account {} does not have se", account.account.username);
+                        if let Some(url) =
+                            settlement_engines.get(account.account.asset_code.as_str())
```
Comment (kincaidoneil) [inline crates/interledger-store-redis/src/store.rs]: What if you're running multiple settlement engines for the same asset, e.g. XRP on-ledger and XRP paychan? (Common scenario on old live network). In that case, do you still have to the set URL for each account?

**Comment by kincaidoneil** [comment]
Also resolves #178  👀

File: crates/interledger-store-redis/src/store.rs (hunk 3 above)
Comment (emschwartz) [reply crates/interledger-store-redis/src/store.rs]: Yes

File: crates/interledger-store-redis/src/store.rs [hunk 4]
```diff
@@ -1767,6 +1747,55 @@ fn update_routes(
...
+            |((connection, settlement_engines), (_, mut accounts)): (
+                LoadSettlementEnginesResult,
+                LoadAccountsResult,
+            )| {
+                debug!(
+                    "settlement engines: {:?}, accounts: {:?}",
+                    settlement_engines, accounts
+                );
+                for account in accounts.iter_mut() {
+                    if account.account.settlement_engine_url.is_none() {
```
Comment (dora-gt) [inline crates/interledger-store-redis/src/store.rs]: Just a question, does this work by just setting SE?
There isn't any initial process?

File: crates/interledger-api/src/routes/node_settings.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (dora-gt) [reply crates/interledger-api/src/routes/node_settings.rs]: ^ this might not be true. If you assume that people add these *once* when they initially set up their nodes, it seems sufficient to provide `set` function.

File: crates/interledger-store-redis/src/store.rs (hunk 4 above)
Comment (dora-gt) [reply crates/interledger-store-redis/src/store.rs]: For example, https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-api/src/routes/accounts.rs#L151

File: crates/interledger-store-redis/src/store.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (emschwartz) [reply crates/interledger-store-redis/src/store.rs]: It's a bit janky but I finally got it. Left a TODO in case we figure out a way to clean up the script

File: crates/interledger-store-redis/src/store.rs (hunk 4 above)
Comment (emschwartz) [reply crates/interledger-store-redis/src/store.rs]: Ooh good catch! You're totally right

Comment (emschwartz) [reply crates/interledger-store-redis/src/store.rs]: Implemented in https://github.com/interledger-rs/interledger-rs/pull/339/commits/92092c1384f87f2c8b947614959c2b065f1c24e6

Comment (emschwartz) [reply crates/interledger-store-redis/src/store.rs]: Implemented in https://github.com/interledger-rs/interledger-rs/pull/339/commits/92092c1384f87f2c8b947614959c2b065f1c24e6

File: crates/interledger-store-redis/src/store.rs (hunk 3 above)
Comment (kincaidoneil) [reply crates/interledger-store-redis/src/store.rs]: Should we support that? (e.g. a custom identifier for each settlement engine instance, which could be the asset code, but is more extensible?)

**Comment by emschwartz** [comment]
The original commit in this PR is currently causing the settlement tests to fail and I can't figure out why right now. I'll work on this later.

It seemed like the problem could be a lua script issue but the main problem also shows up without the commit that changes load accounts to use a lua script.

**Comment by emschwartz** [comment]
The failing test made me realize there were actually a bunch of problems with BTP and CCP so I added some fixes and an additional test to fix the other issues

File: crates/interledger-store-redis/src/store.rs (hunk 3 above)
Comment (emschwartz) [reply crates/interledger-store-redis/src/store.rs]: I don't think so because then you need to configure each account with that identifier (that isn't the `asset_code`), so at that point you might as well just set the URL on the account

**Comment by emschwartz** [comment]
Note the three_node test still seems somewhat flaky on CI (see failing build [here]()) but I can't reproduce the issue locally. It might be related to how long we wait for nodes to start up or accounts to be created.

File: crates/interledger-api/src/routes/accounts.rs [hunk 5]
```diff
@@ -501,48 +508,57 @@ where
...
-        Either::B(ok(account))
-    })})
+            });
+
+        // Register the account with the settlement engine
+        // if a settlement_engine_url was configured on the account
+        // of if there is a settlement engine configured for that
+        // account's asset_code
+        default_settlement_engine_fut.join(get_ilp_address_fut).and_then(move |(default_settlement_engine, _)| {
+            let settlement_engine_url = account.settlement_engine_details().map(|details| details.url).or(default_settlement_engine);
```
Comment (dora-gt) [inline crates/interledger-api/src/routes/accounts.rs]: If my recognition is correct, this doesn't look sufficient because... this works in the following case:

- Set global settlement engines -> Add accounts

but the following procedure would not work:

- Add accounts -> Set global settlement engines

Comment (dora-gt) [reply crates/interledger-api/src/routes/accounts.rs]: That said, this might not happen so often.

File: crates/interledger-api/src/routes/accounts.rs [hunk 6]
```diff
@@ -501,48 +508,57 @@ where
...
-                Ok(account)
-            }))
-    } else {
-        Either::B(ok(account))
-    })})
+            });
+
+        // Register the account with the settlement engine
+        // if a settlement_engine_url was configured on the account
+        // of if there is a settlement engine configured for that
```
Comment (gakonst) [inline crates/interledger-api/src/routes/accounts.rs]:
```suggestion
        // or if there is a settlement engine configured for that
```

File: crates/interledger-ccp/src/server.rs [hunk 7]
```diff
@@ -198,6 +202,9 @@ where
                 .map(|index| ilp_address.to_bytes().slice_to(index + 1))
                 .unwrap_or_else(|| ilp_address.to_bytes().clone());
             *self.ilp_address.write() = ilp_address;
+
+            // TODO should we reset our routes and request new ones
```
Comment (gakonst) [inline crates/interledger-ccp/src/server.rs]: Yes. The store's `set_ilp_address` method updates the stored routes to the current routing table, but I agree that we need to update our routes before that operation. I'll try to fix that.

File: crates/interledger-ccp/src/server.rs [hunk 8]
```diff
@@ -1082,7 +1138,7 @@ mod handle_route_control_request {
         assert_eq!(update.from_epoch_index, 0);
         assert_eq!(update.to_epoch_index, 1);
         assert_eq!(update.current_epoch_index, 1);
-        assert_eq!(update.new_routes.len(), 2);
```
Comment (gakonst) [inline crates/interledger-ccp/src/server.rs]: This is because the connector's route is also sent in the first epoch right?

File: crates/interledger-ccp/src/server.rs [hunk 9]
```diff
@@ -695,6 +735,22 @@ where
         // Merge the new routes and withdrawn routes from all of the given epochs
         let mut new_routes: Vec<Route> = Vec::with_capacity(epochs_to_take);
         let mut withdrawn_routes: Vec<Bytes> = Vec::new();
+
+        // Include our own prefix if its the first update
```
Comment (gakonst) [inline crates/interledger-ccp/src/server.rs]: Why only on the first update? What if they rejected it the first time, and then they added us as an account, hence they start accepting it?

File: crates/interledger-ccp/src/server.rs [hunk 10]
```diff
@@ -566,36 +584,51 @@ where
...
-                                let old_route = forwarding_table.get_route(&prefix);
-                                if old_route.is_none() || old_route.unwrap().0.id() != account.id() {
-                                    route.path.insert(0, ilp_address.to_bytes());
-                                    // Each hop hashes the auth before forwarding
-                                    route.auth = hash(&route.auth);
-                                    forwarding_table.set_route(prefix.clone(), account.clone(), route.clone());
-                                    new_routes.push(route);
-                                }
+                        // or that advertise the whole global prefix
+                        let correct_global_prefix = route.prefix.starts_with(&global_prefix[..])
```
Comment (gakonst) [inline crates/interledger-ccp/src/server.rs]: We should definitely include some kind of diagram illustrating this process in the docs. The slides that were shared with me from the ILP Summit do not cover all these cases and it'd be nice to have all the scenarios we want to cover well documented. Also maybe expand the tests

File: crates/interledger-router/src/router.rs [hunk 11]
```diff
@@ -121,7 +116,26 @@ where
                     }),
             )
         } else {
-            error!("No route found for request: {:?}", request);
+            error!(
+                "No route found for request{}: {:?}",
+                {
+                    // Log a warning if the global prefix does not match
+                    let mut segments = (&self.ilp_address as &str).split(|c| c == '.');
```
Comment (gakonst) [inline crates/interledger-router/src/router.rs]: nit: We have [Address.segments()](https://github.com/bstrie/interledger-rs/blob/27d7c60eb03c1d9f6c1f60e8f55dd251e389c7cb/crates/interledger-packet/src/address.rs#L151)

File: crates/interledger-store-redis/tests/accounts_test.rs [hunk 12]
```diff
@@ -78,40 +78,49 @@ fn insert_accounts() {
...
+                });
+                let ilp_address = Address::from_str("test.parent.our_address").unwrap();
+                store
+                    .set_ilp_address(ilp_address.clone())
+                    .and_then(move |_| {
+                        let ret = store.get_ilp_address();
+                        assert_eq!(ilp_address, ret);
+                        store.get_all_accounts().and_then(move |accounts: Vec<_>| {
+                            let mut accounts = accounts.clone();
+                            accounts.sort_by(|a, b| {
```
Comment (gakonst) [inline crates/interledger-store-redis/tests/accounts_test.rs]: nit: You should be able to [derive Eq and PartialEq for Username](https://github.com/bstrie/interledger-rs/blob/51a0faa54f994e2b7dd28c1a65bf50671779386a/crates/interledger-service/src/auth/username.rs#L23) and do this comparison.

File: crates/interledger-stream/src/client.rs [hunk 13]
```diff
@@ -37,21 +37,32 @@ where
...
-            congestion_controller: CongestionController::default(),
-            pending_requests: Cell::new(Vec::new()),
-            delivered_amount: 0,
-            should_send_source_account: true,
-            sequence: 1,
-            rejected_packets: 0,
-            error: None,
+        .and_then(move |account_details| {
+            let source_account = account_details.ilp_address();
+            let source_scheme = source_account.segments().next().expect("Addresses should have a scheme first");
```
Comment (gakonst) [inline crates/interledger-stream/src/client.rs]: This is always guaranteed by usage of the `Address` data type and should never be hit. I guess it's fine to panic here

File: crates/interledger-api/src/routes/accounts.rs (hunk 5 above)
Comment (gakonst) [reply crates/interledger-api/src/routes/accounts.rs]: Each time there's a change in the global settlement engine, we want to iterate over all accounts which use the global and load the account with that address.

@emschwartz note how this is a similar situation with the Account's ILP Address being stored in the account struct instead of being able to dynamically configure it with some extra information which is contained in the store. We could alter the `Account::try_from` to take an optional `settlement_engine_url` which would be the default engine URL for that asset and use that if no url was configured in the account.

File: crates/interledger-api/src/routes/accounts.rs [hunk 14]
```diff
@@ -501,48 +508,57 @@ where
...
-            .map_err(|_| {
-                warp::reject::custom(ApiError::InternalServerError)
-            })
-        )
-    } else {
-        Either::B(ok(()))
-    };
+        // If we added a parent, get the address assigned to us by
+        // them and update all of our routes
+        let get_ilp_address_fut = if account.routing_relation() == RoutingRelation::Parent {
```
[the remark this answers is not in the document]
Comment (gakonst) [reply crates/interledger-api/src/routes/accounts.rs]: yup

File: crates/interledger-ccp/src/server.rs (hunk 8 above)
Comment (emschwartz) [reply crates/interledger-ccp/src/server.rs]: Yes

File: crates/interledger-ccp/src/server.rs (hunk 9 above)
Comment (emschwartz) [reply crates/interledger-ccp/src/server.rs]: In that case I think they will send a `RouteControlRequest` to request all the routes starting from epoch 0. If so, our address will be included

File: crates/interledger-api/src/routes/accounts.rs (hunk 5 above)
Comment (emschwartz) [reply crates/interledger-api/src/routes/accounts.rs]: Good point @dora-gt. Right now, the correct `settlement_engine_url` will be loaded because the lua script that loads the accounts will fill it in with the globally configured one. However, you're correct that it won't create the account on the settlement engine right now.

Comment (emschwartz) [reply crates/interledger-api/src/routes/accounts.rs]: Implemented in https://github.com/interledger-rs/interledger-rs/pull/339/commits/37ff7db829d0a5fd79c65d4648983d87bf169dc7

File: crates/interledger-packet/src/address.rs [hunk 15]
```diff
@@ -156,6 +156,15 @@ impl Address {
         }
     }
 
+    /// Returns the first segment of the address, which is the scheme.
+    /// See [`IL-RFC 15: ILP Addresses](https://github.com/interledger/rfcs/blob/master/0015-ilp-addresses/0015-ilp-addresses.md#allocation-schemes)
+    pub fn scheme(&self) -> &str {
```
Comment (gakonst) [inline crates/interledger-packet/src/address.rs]: FYI we had added that method but decided to remove it in the relevant PR https://github.com/interledger-rs/interledger-rs/pull/75/commits/fde033c11670b0c232a7d77c870a0b402ea3eb76#diff-8c5852cf578f26f54fc6aa011fb65509R151

File: crates/interledger-packet/src/address.rs [hunk 16]
```diff
@@ -343,6 +352,21 @@ mod test_address {
         );
     }
 
+    #[test]
+    fn test_scheme() {
```
Comment (gakonst) [inline crates/interledger-packet/src/address.rs]: These should be moved to https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-packet/src/address.rs#L287

File: crates/interledger-api/src/routes/node_settings.rs [hunk 17]
```diff
@@ -178,14 +179,56 @@ where
...
-                .and_then(move |_| Ok(reply))
+                .and_then(move |_| {
+                    // Create the accounts on the settlement engines for any
+                    // accounts that are using the default settlement engine URLs
+                    // (This is done in case we modify the globally configured settlement
+                    // engine URLs after accounts have already been added)
+
+                    // TODO we should come up with a better way of ensuring
+                    // the accounts are created that doesn't involve loading
+                    // all of the accounts from the database into memory
```
Comment (gakonst) [inline crates/interledger-api/src/routes/node_settings.rs]: We could page over the accounts instead of loading them all together

File: crates/interledger-settlement-engines/tests/eth_xrp_interoperable.rs [hunk 18]
```diff
@@ -187,9 +187,13 @@ fn eth_xrp_interoperable() {
...
 
-    let bob_fut = set_node_settlement_engines(node2_http, bob_settlement_engines, "admin")
-        .join(create_account_on_node(node2_http, alice_on_bob, "admin"))
-        .join(create_account_on_node(node2_http, charlie_on_bob, "admin"));
+    let bob_fut = create_account_on_node(node2_http, alice_on_bob, "admin")
+        .join(create_account_on_node(node2_http, charlie_on_bob, "admin"))
+        // Setting the settlement engines after the accounts are created should
+        // still trigger the call to create their accounts on the settlement engines
+        .and_then(move |_| {
+            set_node_settlement_engines(node2_http, bob_settlement_engines, "admin")
```
Comment (gakonst) [inline crates/interledger-settlement-engines/tests/eth_xrp_interoperable.rs]: nice.

File: crates/interledger-packet/src/address.rs (hunk 15 above)
Comment (emschwartz) [reply crates/interledger-packet/src/address.rs]: True. My bad for suggesting removing it. I think it's a close call on whether it should be part of the address but in this case it seems like it makes sense to include it because otherwise you'd need `unwrap`s elsewhere while it's clear as part of the `Address` definition that that can't panic.

File: crates/interledger-api/src/routes/node_settings.rs (hunk 17 above)
Comment (emschwartz) [reply crates/interledger-api/src/routes/node_settings.rs]: Yup, there's a TODO [here](https://github.com/interledger-rs/interledger-rs/blob/7428c26032672073af6c52843e53a3b4b294b929/crates/interledger-api/src/lib.rs#L92) for that

**Comment by emschwartz** [comment]
I'm going to merge this now. If there are other changes we want to make to this behavior, we can do them in follow up PRs
